### ISSUE TITLE
Dependency manager support

### ISSUE THREAD

**Issue by viteinfinite** [solomidSF/YRCoverFlowLayout#2]
Hi, thanks for the good work. Are you planning to support a dependency manager such as CocoaPods and, if not, why? Are you open to pull requests for this?

**Comment by solomidSF** [comment]
Hi, thanks, you too.

> Are you planning to support a dependency manager such as CocoaPods and, if not, why?

Yea, I want to integrate cocoa pods, just didn't investigate how to do it yet.

> Are you open to pull requests for this?

Sure

**Comment by 0x0c** [comment]
It's very nice library!
I need to use this with CocoapPods too.

Please try this to add podspec.
https://guides.cocoapods.org/making/making-a-cocoapod.html

**Comment by solomidSF** [comment]
Done
http://cocoapods.org/pods/YRCoverFlowLayout
