### ISSUE TITLE
How to get cell index is in the front? 

### ISSUE THREAD

**Issue by aaasifrz9** [solomidSF/YRCoverFlowLayout#3]

**Comment by AlexNsbmr** [comment]
Hi @aaasifrz9 you can have the cell indexPath of the selected cell like this:

`NSIndexPath *indexPath = [_collectionView indexPathForItemAtPoint:[self.view convertPoint:[self.view center] toView:_collectionView]];`

**Comment by maulikshahiod** [comment]
not working your answer

**Comment by solomidSF** [comment]
Try to divide collection view content offset by collection view width.
