### ISSUE TITLE
scrollToItemAtIndexPath not working properly

### ISSUE THREAD

**Issue by AlexNsbmr** [solomidSF/YRCoverFlowLayout#4]
When using `scrollToItemAtIndexPath: atScrollPosition: animated:` programmatically with the `UICollectionView` the scroll doesn't work properly.
It does scroll, but not enough to center the cell to the desired indexPath.

Do you have an idea how we could fix this ?

Thanks for this awesome library!

**Comment by solomidSF** [comment]
@AlexNsbmr 

As a quick fix solution I suggest you to scroll not to concrete item, but page like this:
`collectionView.contentOffset = (CGPoint){indexPath.row * collectionView.bounds.size.width, 0};`

The main design here is that one cell occupies whole page and your content is centered in it and nearby cells are moving, thus their frame is dynamic and collection view scrolls to whatever current value is.

**Comment by AlexNsbmr** [comment]
@solomidSF 
Thank you so much for your quick answer. 

Adjusting the `UICollectionView` content offset works perfectly. 

I'll close this ticket.

**Comment by maryamfekri** [comment]
but how we can do that with animation though ? scrollToIndexPath has a smooth animation

**Comment by maryamfekri** [comment]
and putting it into `	UIView.animate(withDuration: 0.2) { } `  will make a non pleasant animation :(

**Comment by maryamfekri** [comment]
nvm, 
in Swift: I was setting `collectionView.contentOffset = CGPoint(x: xPoint, y: 0)`
but if you use : `self.collectionView.setContentOffset(CGPoint(x: xPoint, y: 0), animated: true)`  then the animation is working fine 👍
